"""Image-to-texture generation via Hunyuan3D-2GP's paint pipeline ONLY --
bakes a new texture (and UV, via xatlas -- see hy3dgen's own
texgen/utils/uv_warp_utils.py) onto an EXISTING mesh, skipping shape
generation (hunyuan_wrapper.py's i23d_worker) entirely. Backs /gen_texture:
repaint a mesh you already have (generated by /gen_model or supplied some
other way) from a different reference image, without regenerating geometry.

Runs INSIDE the vendor/hunyuan3d-2gp venv (its own torch/mmgp/hy3dgen build,
see hunyuan_wrapper.py's docstring for why), invoked as:

    <vendor>/hunyuan3d-2gp/venv/bin/python gen3d/texture_wrapper.py \\
        --vendor-dir <vendor>/hunyuan3d-2gp --mesh <path.glb> --image <path> \\
        --output <path.glb> [--profile 4]

Not loading i23d_worker means a smaller VRAM footprint and shorter run than
the combined pipeline -- ~5.3 min for the texture stage alone, see 3dtodo.md's
timing table (318s at profile 4 on 6 GB).
"""
import argparse
import os
import sys
import time

parser = argparse.ArgumentParser()
parser.add_argument("--vendor-dir", required=True, help="path to the cloned Hunyuan3D-2GP repo")
parser.add_argument("--mesh", required=True, help="existing mesh to repaint (.glb/.gltf/.obj/...)")
parser.add_argument("--image", required=True, help="reference image for the new texture")
parser.add_argument("--output", required=True, help="output .glb path")
parser.add_argument("--profile", type=int, default=4, help="mmgp offload profile")
args = parser.parse_args()

sys.path.insert(0, args.vendor_dir)
os.chdir(args.vendor_dir)  # hy3dgen resolves some of its own asset paths relative to cwd

os.environ.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "0")

import trimesh
import torch
from PIL import Image

from mmgp import offload
from hy3dgen.texgen import Hunyuan3DPaintPipeline


def vram_used():
    return torch.cuda.memory_allocated() / 1024**3, torch.cuda.max_memory_allocated() / 1024**3


print("=== Loading texture model (Hunyuan3D-2) ===")
t0 = time.time()
texgen_worker = Hunyuan3DPaintPipeline.from_pretrained("tencent/Hunyuan3D-2")
print(f"texgen model loaded in {time.time()-t0:.1f}s")

pipe = offload.extract_models("texgen_worker", texgen_worker)
texgen_worker.models["multiview_model"].pipeline.vae.use_slicing = True

profile = args.profile
kwargs = {}
if profile != 1 and profile != 3:
    kwargs["budgets"] = {"*": 2200}
print(f"=== Using offload profile {profile} ===")
offload.default_verboseLevel = 1
offload.profile(pipe, profile_no=profile, verboseLevel=1, **kwargs)

print(f"=== Loading mesh: {args.mesh} ===")
mesh = trimesh.load(args.mesh, force="mesh")

print(f"=== Preparing reference image: {args.image} ===")
image = Image.open(args.image).convert("RGBA")

torch.cuda.reset_peak_memory_stats()
print("=== Generating texture (baked to new UV) ===")
t0 = time.time()
mesh = texgen_worker(mesh, image=image)
t_tex = time.time() - t0
alloc, peak = vram_used()
print(f"texture generated in {t_tex:.1f}s | vram now={alloc:.2f}GB peak={peak:.2f}GB")

mesh.export(args.output)
print(f"=== DONE. total={t_tex:.1f}s. Saved to {args.output} ===")
